### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by tbsvttr** [rubenkaiser/parcel-plugin-html-partials#3]
Hey. Thanks for your work with this!

Hot reload when a partial is changed would be _very_ nice.

Have you took a look at https://github.com/posthtml/posthtml-include? It implements something rather similar to your project.

**Comment by rubenkaiser** [comment]
Thanks for you interest in this package. I will look into this soon. Hot reload was already on my radar but it involves quite some changes. I'll keep you updated.

The package you are referring to helps process html files with javascript which is quite different from this plugin where the html is checked for partial tags where html should be.

**Comment by pepa-linha** [comment]
Please... 👍🏼

**Comment by rubenkaiser** [comment]
Been a long time since this issue was opened. With Parcel 2 I've updated the package and I think the default hot reloading with Parcel 2 should now be working.
