### ISSUE TITLE
Partials not being rendered in Parcel 2.7

### ISSUE THREAD

**Issue by mrjcgoodwin** [rubenkaiser/parcel-plugin-html-partials#4]
Hi, I'm experimenting with your plugin and Parcel for the first time. I can't get any partials to render - the Parcel server just spits out the partial 'include' tag as a text string instead of rendering the referenced partial file. Am I doing something stupid?!

HTML looks like:

'<body>
    <div id="main" class="container">

        <div class="row">
            <div class="col-lg-3">

                @partial("partials/sidebar_nav.html")

            </div>

            <div class="col"></div>
        </div>

    </div>
</body>'

**Comment by rubenkaiser** [comment]
After the changes did you restart the parcel bundler? The plugin does not implement hot reloading. After changes in the partials a restart is required.

**Comment by mrjcgoodwin** [comment]
> 

Hi, thanks for the quick response.
Yes I'm pretty sure I did. I definitely rebuilt a couple of times so that would have done it.

I'm using posthtml-include now instead which is doing the trick, but will give your one another test soon to confirm.

**Comment by rubenkaiser** [comment]
I'll have a look soon. Haven't updated this package in a while therefore some parcel update might have broken something

**Comment by rubenkaiser** [comment]
@mrjcgoodwin I've just released a new version under a new name since Parcel 2 has a new convention for plugins.
I've updated the readme on how to install and config.
